### PR TITLE
Added contact details to CV

### LINKED ISSUE #6: Addition of contact info to the templates
## Type of Issue
- [x] Feature
- [ ] Bug
- [ ] Documentation

#### This issue requires work on the following:
1. Addition of contact info to the CV templates would be an enhancement
2. Contact info like LinkedIn, GitHub, Mobile and Email would suffice.

### PR DESCRIPTION
**Pull request by kwennB**
fixes #6 

## Proposed Changes

- add contact details ( Linkedin, GitHub, phone, and email) to all 3 templates)

### CODE REVIEW

**Comment by praneeth-rdy** [comment]
Hi @kwennB 

Thanks for the PR. I'll review it by EOD today.

**Comment by kwennB** [comment]
> Hi @kwennB 
> 
> 
> 
> Thanks for the PR. I'll review it by EOD today.

Thank you @praneeth-rdy

**Review by praneeth-rdy — CHANGES_REQUESTED** [review]
Hi @kwennB 
Did you observe the other alignment differences in the CV templates due to the addition of contact details?

Please check and  fix these:
- The text got aligned to left in template-1 which is creating unnecessary space towards the right and not according to the actual IITKGP template.
- College logo position is hampered in template-2.
- Better to have the contact column at the right-extreme in template-3.

Could you please fix these?

**Comment by kwennB** [comment]
> Hi @kwennB 
> 
> Did you observe the other alignment differences in the CV templates due to the addition of contact details?
> 
> 
> 
> Please check and  fix these:
> 
> - The text got aligned to left in template-1 which is creating unnecessary space towards the right and not according to the actual IITKGP template.
> 
> - College logo position is hampered in template-2.
> 
> - Better to have the contact column at the right-extreme in template-3.
> 
> 
> 
> Could you please fix these?

Hi @praneeth-rdy 
Thank you for the feedback. 
Yes I will work on the fixes.

**Comment by kwennB** [comment]
Hello @praneeth-rdy I have pushed the fixes to this PR.

**Comment by kwennB** [comment]
Hello @praneeth-rdy Did you get a chance to review the edits on the PR?

**Comment by praneeth-rdy** [comment]
Hi @kwennB 
Sorry for the delay. I was quite occupied last week.
I've reviewed the changes and found the following issues.
1) In template-1, the contact info isn't centred and the increase in contact URL length is pushing the header towards the left.
2) In template-3, the color of the contact section is too overlapping with the background white. It's only visible when we hover over it.
3) Editing the contact is not updating the href of the contact.

Could you fix these? Let me know If you feel it's too heavy. I can hop in and work on this issue.

**Review by praneeth-rdy — CHANGES_REQUESTED** [review]
Hi @kwennB 

Sorry for the delay. I was quite occupied last week.

I've reviewed the changes and found the following issues.
1) In template-1, the contact info isn't centred and the increase in contact URL length is pushing the header towards the left.
2) In template-3, the color of the contact section is too overlapping with the background white. It's only visible when we hover over it.
3) Editing the contact is not updating the href of the contact.

Could you fix these? Let me know If you feel it's too heavy. I can hop in and work on this issue.

**Comment by kwennB** [comment]
Hi @praneeth-rdy 

I apologize for the late response, I'll give them a short first as soon as I can.

**Comment by praneeth-rdy** [comment]
Hi @kwennB,

Are you still interested in continuing with this PR?

Best Regards,
@praneeth-rdy

**Pull request closed without merging**
